version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - TZ="Asia/Tokyo"
    ports:
      - "3305:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
